repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        language: python
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=120
        language: python

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: # arguments to configure flake8
              # making isort line length compatible with black
          - "--max-line-length=120"
        language: python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        language: python
        additional_dependencies:
          - 'pydantic'
          - 'sqlalchemy-stubs'
          - 'types-requests'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        language: python
      - id: end-of-file-fixer
        language: python
      - id: check-merge-conflict
        language: python
