version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:80"
    # probably a hack: createsuperuser would fail if issued on existing DB (as the user already exists)
    # so to allow build command to finish and run the container, we force to ignore the error
    command: /app/start.sh
    volumes:
      - ./management_interface:/app
    environment:
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-hans_admin@thepsc.co.uk}"
      - "HANS_MI_DEBUG=${HANS_MI_DEBUG:-TRUE}"
      - "GUNICORN_LOGLEVEL=${GUNICORN_LOGLEVEL}"
      - "GUNICORN_WORKERS=${GUNICORN_WORKERS}"
      - "MANAGEMENT_API_BASE_URL=${MANAGEMENT_API_BASE_URL}"
      - "COGNITO_ENDPOINT=${COGNITO_ENDPOINT}"
      - "COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}"
      - "COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}"
      - "COGNITO_JWKS_URI=${COGNITO_JWKS_URI}"
      - "COGNITO_REDIRECT_URI=${COGNITO_REDIRECT_URI}"
    depends_on:
      - db
  db:
    image: postgres:15.2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
